tracker_create:
    path:       /error
    defaults:   { _controller: LigneusTrackerBundle:Error:create, _format: json }
    methods:    [POST]

tracker_heartbeat:
    path:       /ping/heartbeat
    defaults:   { _controller: LigneusTrackerBundle:Ping:heartbeat, _format: json }
    methods:    [POST, OPTIONS]
