language: php
php:
  - '7.0'

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y wget

install:
    - wget http://get.sensiolabs.org/security-checker.phar

script:
    - php security-checker.phar security:check composer.lock
