<?php

namespace AppBundle\Repository;

/**
 * InicidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InicidentRepository extends \Doctrine\ORM\EntityRepository
{
}
