<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Source;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTeamsBySource(Source $source)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Team', 't')
            ->join('t.sources', 's')
            ->addSelect('s')
            ->where('s.id = :sourceId')
            ->setParameter('sourceId', $source->getId())
            ->getQuery()
        ;

        $result = $query->getResult();

        return $result;
    }
}
