# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    exc.incident_graph:
        class: AppBundle\Service\IncidentGraphService
        arguments:
            - "@doctrine"
    exc.exception_type_graph:
        class: AppBundle\Service\ExceptionTypeGraphService
        arguments:
            - "@doctrine"
    exc.application:
        class: AppBundle\Service\ApplicationService
        arguments:
            - "%exc.ping_threshold%"
            - "@doctrine"
    exc.string_extension:
        class: AppBundle\Twig\StringExtension
        public: false
        tags:
            - { name: twig.extension }
    exc.app_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@exc.application"
    exc.date_extension:
        class: AppBundle\Twig\DateExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@exc.application"
    exc.slack:
        class: TrackerBundle\Service\SlackService
    exc.mail:
        class: TrackerBundle\Service\MailService
        arguments:
            - "@mailer"
            - "%exc.mail_from%"
    exc.tracker:
        class: TrackerBundle\Service\TrackerService
        arguments:
            - "@exc.slack"
            - "@validator"
            - "@doctrine"
            - "@router"
            - "@exc.mail"
            - "@templating"
            - "@exc.application"
