api_incidents_collection:
    path:  /
    defaults: { _controller: ApiBundle:Incident:collection }

api_incidents_entity:
    path:  /{incidentId}
    defaults: { _controller: ApiBundle:Incident:entity }

api_incidents_count:
    path:  /count
    defaults: { _controller: ApiBundle:Incident:entityTotalCount }
