Ligneus\DataBundle\Entity\Incident:
    properties:
        message:
            - NotBlank: ~
        occurrence:
            - DateTime: ~
        statusCode:
            - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
Ligneus\DataBundle\Entity\Application:
    properties:
        name:
            - NotBlank: ~
        appkey:
            - NotBlank: ~
        url:
            - Url: ~
