api_applications_collection:
    pattern:  /
    defaults: { _controller: ApiBundle:Application:collection }

api_applications_entity:
    pattern:  /{applicationId}
    defaults: { _controller: ApiBundle:Application:entity }

api_applications_entity_incidents:
    pattern:  /{applicationId}/incidents
    defaults: { _controller: ApiBundle:Application:entityIncidents }
