incidents_like:
    path:       /like/{incidentId}
    defaults:   { _controller: AppBundle:Incident:like }

incidents_detail:
    path:       /{incidentId}
    defaults:   { _controller: AppBundle:Incident:detail }

incidents_silence:
    path:       /{incidentId}/silence
    defaults:   { _controller: AppBundle:Incident:silence }
