index:
    path:       /
    defaults:   { _controller: FrameworkBundle:Redirect:redirect, route: dashboard, permanent: true }

dashboard:
    path:       /dashboard
    defaults:   { _controller: AppBundle:App:dashboard }

#sources
sources_collection:
    path:       /sources
    defaults:   { _controller: AppBundle:Source:collection }
