index:
    path:     /
    defaults: { _controller: AppBundle:Page:index }

dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Page:dashboard }

applications:
    resource: "@AppBundle/Resources/config/Application/routing.yml"
    prefix:   /applications

stream:
    path:     /stream
    defaults: { _controller: AppBundle:Page:stream }

incidents:
    resource: "@AppBundle/Resources/config/Incident/routing.yml"
    prefix:   /incidents
