applications_collection:
    path:       /
    defaults:   { _controller: LigneusAppBundle:Application:collection }

applications_create:
    path:       /create
    defaults:   { _controller: LigneusAppBundle:Application:create }

applications_object:
    path:       /{applicationId}
    defaults:   { _controller: LigneusAppBundle:Application:object }

applications_update:
    path:       /{applicationId}/update
    defaults:   { _controller: LigneusAppBundle:Application:update }

applications_delete:
    path:       /{applicationId}/delete
    defaults:   { _controller: LigneusAppBundle:Application:delete }

applications_heartbeat:
    path:       /{applicationId}/heartbeats
    defaults:   { _controller: LigneusAppBundle:Application:heartbeats }

applications_heartbeat_delete:
    path:       /{applicationId}/heartbeats/{heartbeatId}/delete
    defaults:   { _controller: LigneusAppBundle:Application:deleteHeartbeat }

applications_heartbeat_monitor:
    path:       /{applicationId}/heartbeats/{heartbeatId}/monitor
    defaults:   { _controller: LigneusAppBundle:Application:monitorHeartbeat }

applications_heartbeat_edit_alias:
    path:       /{applicationId}/heartbeats/{heartbeatId}/alias/edit
    defaults:   { _controller: LigneusAppBundle:Application:editHeartbeatAlias }
