<?php

namespace Proxies\__CG__\DataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Heartbeat extends \DataBundle\Entity\Heartbeat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'ip', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'lastPing', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'application', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'monitor', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'alias', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'notified', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'incidents'];
        }

        return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'ip', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'lastPing', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'application', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'monitor', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'alias', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'notified', '' . "\0" . 'DataBundle\\Entity\\Heartbeat' . "\0" . 'incidents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Heartbeat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', [$ip]);

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', []);

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastPing($lastPing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastPing', [$lastPing]);

        return parent::setLastPing($lastPing);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastPing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastPing', []);

        return parent::getLastPing();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonitor($monitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonitor', [$monitor]);

        return parent::setMonitor($monitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonitor', []);

        return parent::getMonitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', [$alias]);

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', []);

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotified($notified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotified', [$notified]);

        return parent::setNotified($notified);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotified', []);

        return parent::getNotified();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplication(\DataBundle\Entity\Application $application = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplication', [$application]);

        return parent::setApplication($application);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplication', []);

        return parent::getApplication();
    }

    /**
     * {@inheritDoc}
     */
    public function addIncident(\DataBundle\Entity\Incident $incident)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIncident', [$incident]);

        return parent::addIncident($incident);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIncident(\DataBundle\Entity\Incident $incident)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIncident', [$incident]);

        return parent::removeIncident($incident);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidents', []);

        return parent::getIncidents();
    }

}
