api_applications:
    resource: "@LigneusApiBundle/Resources/config/Application/routing.yml"
    prefix:   /applications

api_incidents:
    resource: "@LigneusApiBundle/Resources/config/Incident/routing.yml"
    prefix:   /incidents

api_testSlack:
    path:       /testSlack
    defaults:   { _controller: LigneusApiBundle:Misc:testSlack, _format: json }
    methods:    [POST]
